<p><?=$this->translate("Are you sure you want to delete");?>
'<?php echo $this->escape($this->entry['template']); ?>' for wlabel
'<?php echo $this->escape($this->entry['id_wlabel']); ?>'?
</p>
<form action="<?= $this->url(array('module' => 'admin','controller' => 'templates','action'=>'delete'), 'default', true) ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->entry['id']; ?>" />
<input type="submit" name="del" value="<?=$this->translate("Yes");?>"/>
<input type="submit" name="del" value="<?=$this->translate("No");?>" />
</div>