<p><?=$this->translate("Welcome");?>, <?php echo Zend_Auth::getInstance()->getIdentity()->user_name ?>.<br>
<?=$this->translate("Ussing role");?>: <?php echo $this->list['role']; ?>.<br>
<?=$this->translate("Available resources");?>:
<?php 
	$a=0;
	foreach ($this->list['allowed'] as $resource => $access) :?> 
<div><?=$a;?> User: 
<?php 
$re=explode(":",$resource);
$module=$re[0];
$rs=explode(" - ",$re[1]);
$controller=$rs[0];
$accion=$rs[1];
?>
	<?php 
		$a++;
		if (is_object(Zend_Auth::getInstance()->getIdentity())) 
			echo Zend_Auth::getInstance()->getIdentity()->user_name; 
		else echo "Unknown";?>  
	is <?=$access=='allowed'?'<font color="green">allowed</font>':'<font color="red">denied</font>' ?> <?=$this->translate("access to");?> <?php echo $resource ?>
	<a href="<?php echo $this->url(array('module'=>$module,
									 	 'controller'=>$controller,
									 	 'action'=>$accion));
			?>">Link</a>
</div> 
<?php endforeach; ?>
