<?php
/**
 * Default home page view
 *  
 * @author
 * @version
 */

$this->headTitle('New Zend Framework Project');
$this->placeholder('title')->set('Welcome');
?>
<p>Usuario actual: <?php echo Zend_Auth::getInstance()->getIdentity()->user_name ?>.<br>
Usando rol: <?php echo $this->list['role']; ?>.<?= $this->form ?><br>
Available resources:
<?php
//Zend_Debug::dump($this->list);
	$a=0;
	foreach ($this->list['allowed'] as $resource => $access) :?> 
<div>
<?php 
$re=explode(":",$resource);
$module=$re[0];
$rs=explode(" - ",$re[1]);
$controller=$rs[0];
$accion=$rs[1];
?>
	<?=$a;?> Rol: 
	<?php 
		$a++;
		if (is_object(Zend_Auth::getInstance()->getIdentity())) 
			echo $this->list['role']; 
		else echo "Unknown";
            $resource = str_replace(' ', '', $resource);
            $resource_split1 = explode('-', $resource);
            $resource_split2 = explode(':', $resource_split1[0]);
        ?>
	is <?=$access=='allowed'?'<font color="green">allowed</font>':'<font color="red">denied</font>' ?> 
        access to
        <a href="<?php echo $this->url(array('controller'=>$resource_split2[1],'action'=>$resource_split1[1],'module'=>$resource_split2[0]));?>"><?php echo $resource ?></a>
 <a href="<?php echo $this->url(array('module'=>$module,
									 	 'controller'=>$controller,
									 	 'action'=>$accion));
			?>">Link</a>
</div> 
<?php endforeach; ?>