<?php 
$images=explode(',',$this->entries['images']);
//if(!empty($images[0]))
foreach($images as $image):
?>
<span id="containerID<?=$image?>">
	<dl class="product">
		<dt>
			<strong><?=$image?></strong>
			<a href="#"><img width="97" height="82" src="/assets/proyectos/<?=$this->type?>/<?=$this->path?>/<?=$image?>" alt="" /></a>
		</dt>
		<dd>
			<em>356 Kb</em>
			<ul>
				<li><a href="#" class="edit_product">Edit</a></li>
				<li>
					<a class="delete_product" onClick="javascript:return confirm('Deseas borrar esta foto?');" href="javascript:getAjaxResponse('/projects/ajax/deletephoto/id/<?=$this->id?>/foto/<?=$image?>','containerID<?=$image?>')" title="text example">
					Delete</a>
				</li>
			</ul>
		</dd>
	</dl>	
	</span>	
	
<?php endforeach;?>