<p>Seguro que deseas borrar
'<?php echo $this->escape($this->entry['role_name']); ?>'?
</p>
<form action="<?= $this->url(array('module' => 'users','controller' => 'roles','action'=>'delete'), 'default', true) ?>" method="post">
<div>
<input type="hidden" name="role_id" value="<?php echo $this->entry['role_id']; ?>" />
<input type="submit" name="del" value="Si" />
<input type="submit" name="del" value="No" />
</div>