<div class="pagination">
    <div class="pagination_left">
    </div>
    <div class="pagination_right">
        <div class="pagination_right_links">
                <!-- First page link -->
                <?php if (isset($this->previous)): ?>
                      <a href="<?= $this->url(array('page' => $this->first)); ?>">&lt;&lt;</a> |
                <?php else: ?>
                        <span class="disabled">&lt;&lt;</span> |
                <?php endif; ?>

                <!-- Previous page link -->
                <?php if (isset($this->previous)): ?>
                      <a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt;</a> |
                <?php else: ?>
                    <span class="disabled">&lt;</span> |
                <?php endif; ?>

                <!-- Numbered page links -->
                <?php foreach ($this->pagesInRange as $page): ?>
                    <?php if ($page != $this->current): ?>
                        <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a>
                    <?php else: ?>
                        <?= $page; ?>
                    <?php endif; ?>
                <?php endforeach; ?>

                <!-- Next page link -->
                <?php if (isset($this->next)): ?>
                      | <a href="<?= $this->url(array('page' => $this->next)); ?>">&gt;</a> |
                <?php else: ?>
                    | <span class="disabled">&gt;</span> |
                <?php endif; ?>
                    
                <!-- Last page link -->
                <?php if (isset($this->next)): ?>
                      <a href="<?= $this->url(array('page' => $this->last)); ?>">&gt;&gt;</a>
                <?php else: ?>
                    <span class="disabled">&gt;&gt;</span>
                <?php endif; ?>
        </div>
    </div>
 </div>