<div id="navigation"> <!-- Navigation begins here -->
	<div class="sidenav"><!-- Sidenav -->
<?php
$acl = Users_Model_Acl::getInstance();
$list=$acl->listResourceByUser();
$html = array();
foreach ($this->container as $page) 
{
    $permission=$list['allowed'][$page->resource.' - '.$page->privilege];
	if($permission=='allowed'){
		
	    $href = $page->getHref();
	    		if ($href) {
	    			$html[] = "<div class=\"navhead";
//	    			if($page->isActive(true)) $html[] = " selected";
//	    			$html[] = "\"><span><a href=\"{$href}\" title=\"".$this->translate($page->getLabel())."\">".$this->translate($page->getLabel())."</a></span></div>";
	    			$html[] = "\"><span>".$this->translate($page->getLabel())."</span></div>";	            	
	            }
	            else {
	            	$html[] = "<div class=\"navhead";
//	    			if($page->isActive(true)) $html[] = " selected";
	    			$html[] = "\"><span>".$this->translate($page->getLabel())."</span></div>";
	            }
	    $html[] = "<div class=\"subnav\">";
//		if($page->isActive(true))
		    if (!empty($page->pages))
		    {
		        $html[] = "<ul class=\"submenu\">";    	
		        foreach ($page->pages as $subpage) 
		        {            
		        	$permission_sub=$list['allowed'][$subpage->resource.' - '.$subpage->privilege];
					if($permission_sub=='allowed'){
			            $html[] = "<li>";
			            $href = $subpage->getHref();
			            if ($href) {
			            	$html[] = "<a href=\"{$href}\"";
			            	if($subpage->isActive(true)) $html[] = " class=\"selected_lk\"";
			            	$html[] = ">".$this->translate($subpage->getLabel())."</a>";
			            }
			            else $html[] = $this->translate($subpage->getLabel());         
			            $html[] = "</li>";
					}
		        }
		        $html[] = "</ul>";
		    }
		$html[] = "</div>";	    
	}
}
echo join(PHP_EOL, $html);
?>
</div>
</div> <!-- END Navigation -->