<ul>
    <li class="first active"><span class="active"/><a href="<?php echo $this->url(array('module'=>'iturismo','controller'=>'index','action'=>'index'));?>">Index</a></li>
    <li class="first"><a href="<?php echo $this->url(array('module'=>'iturismo','controller'=>'offices','action'=>'index'));?>">Oficinas</a></li>
    <li class="first"><a href="<?php echo $this->url(array('module'=>'iturismo','controller'=>'news','action'=>'index'));?>">Noticias</a></li>
    <li class="first"><a href="<?php echo $this->url(array('module'=>'iturismo','controller'=>'recommended','action'=>'index'));?>">Recomendados</a></li>
    <li class="first"><a href="<?php echo $this->url(array('module'=>'iturismo','controller'=>'images','action'=>'index'));?>">Im&aacute;genes</a></li>
    <li class="first"><a href="<?php echo $this->url(array('module'=>'iturismo','controller'=>'banners','action'=>'index'));?>">Banners</a></li>
    <li class="first"><a target="_blank" href="<?php echo $this->url(array('controller'=>'frontend','action'=>'index'));?>">iPtours</a></li>
</ul>
