	   		
    <?php echo $this->headLink()->setStylesheet($this->baseUrl('/styles/fileuploader/css/fileuploader.css'), 'screen, projection')?>
    <?php echo $this->headLink()->setStylesheet($this->baseUrl('/styles/fileuploader/css/fileuploaderview.css'), 'screen, projection')?>
    <?php echo $this->headScript()->setFile($this->baseUrl('/styles/fileuploader/js/fileuploader.js')); ?>
    

	<div id="insertphoto-modal"">
	<h3>Upload Photo</h3>	
    <div id="file-uploader-demo1">		
		<noscript>			
			<p>Please enable JavaScript to use file uploader.</p>
			<!-- or put a simple form for upload here -->
		</noscript>         
	</div>
	<script>        
        function createUploader(){            
            var uploader = new qq.FileUploader({
                element: document.getElementById('file-uploader-demo1'),
                action: '/projects/ajax/addphoto/project_id/<?=$this->dir;?>',
                debug: true
            });           
        }
        
        // in your app create uploader as soon as the DOM is ready
        // don't wait for the window to load  
        window.onload = createUploader;     
    </script>
    </div>