<p>Formulario para editar Proyectos.</p>
<?php
	//echo $this->form;
?>
<script type="text/javascript">
//<![CDATA[
	dojo.require("dijit.form.Form");
    dojo.require("dijit.dijit");
    dojo.require("dijit.layout.ContentPane");
    dojo.require("dijit.layout.TabContainer");
    dojo.require("dojo.parser");
	dojo.addOnLoad(function() {
	    dojo.forEach(zendDijits, function(info) {
	        var n = dojo.byId(info.id);
	        if (null != n) {
	            dojo.attr(n, dojo.mixin({ id: info.id }, info.params));
	        }
	    });
	    dojo.parser.parse();
	});
  	dojo.require("dijit.Dialog");
    var zendDijits = [{"id":null,"params":{"dojoType":"dijit.form.Form"}}];
//]]>

</script>

<div dojoType="dijit.Dialog" id="dialog1" title="First Dialog" style="height:450px; width:700px"
    execute="alert('submitted w/args:\n' + dojo.toJson(arguments[0], true));">
    <button dojoType="dijit.form.Button" type="submit">OK</button>
</div>

<form enctype="application/x-www-form-urlencoded" isEdit="1" method="post" >
<div style="width: 700px; height: 650px">
    <div dojoType="dijit.layout.TabContainer" style="width: 100%; height: 100%;">
        <div dojoType="dijit.layout.ContentPane" title="General" selected="true">          
            <?php
                echo $this->formgen;
             ?>
        </div>
        <div dojoType="dijit.layout.ContentPane" title="Images" selected="true">          
            <?php
                echo $this->formgal;
             ?>
        </div>
        <div dojoType="dijit.layout.ContentPane" title="Español">
            <?php
                echo $this->formesp;
             ?>
        </div>
        <div dojoType="dijit.layout.ContentPane" title="Catalá">
            <?php
                echo $this->formcat;
             ?>
        </div>
        <div dojoType="dijit.layout.ContentPane" title="English">
            <?php
                echo $this->formeng;
             ?>
        </div>
    </div>
</div>

<?php
	echo $this->formsubmit;
//	echo $this->form;
?>
</form>

<div id="insertphoto-modal" style="display: none"> 
	<h3>Upload Photo</h3> 
	<script type="text/javascript">
		dojo.require("dojo.parser");
		dojo.require("dojo.io.iframe");
		function ioIframeGetJson(x){
			var td = dojo.io.iframe.send({
				url: "/projects/index/addphoto",
				form: "frmIO",
				method: "post",
				content: {fnx:x},
				timeoutSeconds: 5,
				preventCache: true,
				handleAs: "json",
				handle: function(res, ioArgs){
					if(res.status=='Good')
					{
						dojo.byId('status').innerHTML=res.status;
						dojo.byId('textdisplay').value=res.textdata;
					}
					else
						alert('Error1');
					},							
				error: function (res,ioArgs) {alert('Error2')}
			});
		}
		</script>
<!--	<form action="/projects/index/addphoto" id="myform">-->
	<form name="frmIO" id="frmIO" enctype="multipart/form-data" method="post">
					<fieldset>					
						<dt id="subformgal-label">&#160;</dt><dd id="subformgal-element"><fieldset id="fieldset-subformgal"><dl>
						<dt id="imagen_path-label"><label for="imagen_path" class="required">Image (512kb size, jpg,png,gif)</label></dt>
						<dd>

						<input type="file" name="imagen_path" id="imagen_path" /></dd>
<!--						<input class="button" type="submit" value="Send" />-->
<!--						<button type="submit" value="Send" class="button" dojoType="dijit.form.Button" id="submitButton">-->
						<button onclick="ioIframeGetJson(1)" type="submit">Go</button>
					</fieldset>
	</form>	
	<p>
		<strong>Status</strong>&nbsp;
        <span id="status">None</span>
        <br />
		<strong>Response Text</strong> (formatted)<br />
        <textarea id="textdisplay" name="textdisplay" rows="10" cols="40">
        </textarea>
	</p>
	
	
</div> <!-- End #messages -->




<!--	<div class="qq-uploader">-->
<!--		<div class="qq-upload-drop-area" style="display: none;">-->
<!--			<span>Drop files here to upload</span>-->
<!--		</div>-->
<!--		<div class="qq-upload-button" style="overflow: hidden; position: relative; direction: ltr;">Upload a file-->
<!--			<input type="file" multiple="multiple" name="file" style="margin: 0pt; padding: 0pt; position: absolute; right: 0pt; top: 0pt; z-index: 1; font-size: 460px; cursor: pointer; opacity: 0;">-->
<!--		</div>-->
<!--		<ul class="qq-upload-list"></ul>-->
<!--	</div>-->