<?= $this->doctype() ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?= $this->headTitle($this->escape($this->title)) ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">
    <?php echo $this->headLink()->setStylesheet($this->baseUrl('/assets/css/style.css'), 'all')?>	
    <?php echo $this->headLink()->setStylesheet($this->baseUrl('/assets/css/style_wp.css'), 'all')?>
	<?php echo $this->headScript() ?>
    <style>

   
    </style>
	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	<?php echo $this->headScript()->setFile($this->baseUrl('/assets/js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9')); ?>
	
    <!-- Fav and touch icons -->
    <?php //= $this->headLink(array('rel' => 'shortcut icon','href' => $this->baseUrl().'/images/favicon.ico'),'PREPEND') ?>
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

	<?= $this->render('partials/navbar.phtml') ?>

    <?= $this->render('partials/carousel.phtml') ?>

    
    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">
	 <?php //= $this->render('partials/marketing.phtml') ?>
	 <?= $this->layout()->content ?>
	 
	 <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2013 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

    </div><!-- /.container -->
    





    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/assets/js/jquery.js"></script>
    <script src="/assets/js/bootstrap-transition.js"></script>
    <script src="/assets/js/bootstrap-alert.js"></script>
    <script src="/assets/js/bootstrap-modal.js"></script>
    <script src="/assets/js/bootstrap-dropdown.js"></script>
    <script src="/assets/js/bootstrap-scrollspy.js"></script>
    <script src="/assets/js/bootstrap-tab.js"></script>
    <script src="/assets/js/bootstrap-tooltip.js"></script>
    <script src="/assets/js/bootstrap-popover.js"></script>
    <script src="/assets/js/bootstrap-button.js"></script>
    <script src="/assets/js/bootstrap-collapse.js"></script>
    <script src="/assets/js/bootstrap-carousel.js"></script>
    <script src="<?php $this->baseUrl('/assets/js/bootstrap-typeahead.js');?>"></script>
    <script>
      !function ($) {
        $(function(){
          // carousel demo
          $('#myCarousel').carousel()
        })
      }(window.jQuery)
    </script>
    <script src="/assets/js/holder/holder.js"></script>
  </body>
</html>
