<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-Language" content="es" />
        <meta http-equiv="imagetoolbar" content="no" />
        <meta name="language" content="en" />
        <meta name="title" content="<?=$this->escape($this->title);?>" lang="en" />
		<meta name="resource-type" content="document" />
		<meta name="keywords" content="Jansada, de la Villa, de Paauw, arquitectes, barcelona,  spain, europe, " />
		<meta name="description" lang="en" content="Jansana, de la Villa, de Paauw, arquitectes SLP." />
		<meta name="Author" content="Agustín Calderón agustincl[at]gmail.com" />		
		<meta name="rating" content="general" />
		<meta name="revisit-after" content="30 Days" />
		<meta name="distribution" content="global" /> 
		<meta name="copyright" content="jdvdp" />
		<meta name="robots" content="all,index" />
		<meta name="language" content="Spanish,English,Català" />
		<meta name="doc-type" content="Web Page" />        
        <?= $this->headTitle($this->escape($this->title)) ?>
        <?= $this->headLink(array('rel' => 'shortcut icon','href' => $this->baseUrl().'/images/favicon.ico'),'PREPEND') ?>
        <!-- Framework CSS -->
        <style type="text/css">
		<!--
		
		html, 
		body, 
		.pageright, 
		.pageleft 						{  min-height: 100%; width: 100%; height: 100%; overflow: hidden; }
		.pageright 						{ position: fixed; top: 0; left: 0; }
		
		-->
		
		</style>
        <?php echo $this->headLink()->setStylesheet($this->baseUrl('/styles/frontend/css/reset.css'), 'all')?>
        <?php echo $this->headLink()->setStylesheet($this->baseUrl('/styles/frontend/css/white.css'), 'screen, projection')?>
        <?php echo $this->headLink()->setStylesheet($this->baseUrl('/styles/frontend/css/centerme.css'), 'screen, projection')?>
        
		              
        <?php echo $this->headScript() ?>
        <!-- Jquery -->
        <?php echo $this->headScript()->setFile($this->baseUrl('/styles/frontend/js/jquery-1.4.min.js'), 'text/javascript'); ?>
        <?php echo $this->headScript()->setFile($this->baseUrl('/styles/frontend/js/jquery.easing.js'), 'text/javascript'); ?>
        <!-- ToolTip-->
        <?php echo $this->headScript()->setFile($this->baseUrl('/styles/frontend/js/jquery.tipsy.js'), 'text/javascript'); ?>
        <!-- Jscroolpane jscripts and css -->
        <?php echo $this->headLink()->setStylesheet($this->baseUrl('/styles/frontend/css/jScrollPane.css'), 'screen, projection')?>
        <?php echo $this->headScript()->setFile($this->baseUrl('/styles/frontend/js/mouse_wheel.js'), 'text/javascript'); ?>
        <?php echo $this->headScript()->setFile($this->baseUrl('/styles/frontend/js/jScrollPane.js'), 'text/javascript'); ?>
        <!--NivoSlider -->
        <?php echo $this->headLink()->setStylesheet($this->baseUrl('/styles/frontend/css/nivo-slider.css'), 'screen, projection')?>
        <?php echo $this->headScript()->setFile($this->baseUrl('/styles/frontend/js/jquery.nivo.slider.pack.js'), 'text/javascript'); ?>
        <script type="text/javascript">
		$(window).load(function() {
			$('#slider').nivoSlider({
				effect:'fade', // sliceDown, sliceDownLeft, sliceUp, sliceUpLeft, sliceUpDown, sliceUpDownLeft, fold, fade, random
				animSpeed:500,
				pauseTime:3000,
				directionNav:true, //Next and Prev
				directionNavHide:true, //Only show on hover
				controlNav:false, //1,2,3...
				pauseOnHover:true, //Stop animation while hovering
				beforeChange: function(){},
				afterChange: function(){}
			});
			
						
					
		});
		</script>
		<!--Cufon -->
		<?php //echo $this->headScript()->setFile($this->baseUrl('/styles/frontend/js/cufon/cufon-yui.js'), 'text/javascript'); ?>
        <?php //echo $this->headScript()->setFile($this->baseUrl('/styles/frontend/js/cufon/Titillium.js'), 'text/javascript'); ?>
        
        <?php echo $this->headScript()->setFile($this->baseUrl('/styles/frontend/js/custom.js'), 'text/javascript'); ?>
        
        <!--[if IE 6]>
		<script src="DD_belatedPNG.js" type="text/javascript"></script>
		<script>
		  /* EXAMPLE */
		  DD_belatedPNG.fix('*');
		  
		  /* string argument can be any CSS selector */
		  /* .png_bg example is unnecessary */
		  /* change it to what suits you! */
		</script>
		<![endif]--> 
		
        <?php
        if ($this->dojo()->isEnabled()) {
            $this->dojo()->setDjConfigOption('isDebug', false)
                ->setDjConfigOption('parseOnLoad', true)
                ->setDjConfigOption('locale', 'es-es')
//                ->setLocalPath($this->baseUrl(DOJO_PATH.'/dojo/dojo.js'))
                ->setLocalPath($this->baseUrl('/scripts/js/release/ag/dojo/dojo.js'))
                ->addStyleSheetModule('dijit.themes.tundra');
//                ->requireModule("dojo.parser");
            echo $this->dojo();
        }
        ?>

</head>
<body>


<div id="wrap">
	
	<div id="main">
	<div class="content">	
    	<!-- .logo -->
        <div class="logo">
			<a href="/frontend/index"><img src="/styles/frontend/images/logo.png" alt="" /></a>
		</div>
        <!-- .logo -->
		
		<div class="clear"></div>
		
	    <!-- .main_menu -->
        <div class="main_menu">
	    <!-- Menu Lists -->    	
	    <?php ?>
			<ul id="side-nav">		
				<li><a href="/frontend/index/equipo" class="parent no-child  <?=($this->menu=='Equipo')?'current':'';?>"><?=$this->translate('Equipo');?></a></li>
				<li><a href="#" class="parent no-child <?=($this->menu=='Proyectos')?'current':'';?>"><?=$this->translate('Proyectos');?></a>
					<ul <?=$this->block;?>>
						<li><a href="/frontend/index/proyectos/type/planeamiento" class="parent no-child <?=($this->menu=='planeamiento')?'current':'';?>"><?=$this->translate('Planeamiento');?></a></li>						
						<li><a href="/frontend/index/proyectos/type/paisaje" class="parent no-child <?=($this->menu=='paisaje')?'current':'';?>"><?=$this->translate('paisaje');?></a></li>
						<li><a href="/frontend/index/proyectos/type/parques_y_jardines" class="parent no-child <?=($this->menu=='parques_y_jardines')?'current':'';?>"><?=$this->translate('parques y jardines');?></a></li>										
						<li><a href="/frontend/index/proyectos/type/diseno_urbano" class="parent no-child <?=($this->menu=='diseno_urbano')?'current':'';?>"><?=$this->translate('diseño urbano');?></a></li>
						<li><a href="/frontend/index/proyectos/type/interiorismo" class="parent no-child <?=($this->menu=='interiorismo')?'current':'';?>"><?=$this->translate('interiorismo');?></a></li>
						<li><a href="/frontend/index/proyectos/type/nueva_planta" class="parent no-child <?=($this->menu=='nueva_planta')?'current':'';?>"><?=$this->translate('nueva planta');?></a></li>
						<li><a href="/frontend/index/proyectos/type/rehabilitacion" class="parent no-child <?=($this->menu=='rehabilitacion')?'current':'';?>"><?=$this->translate('rehabilitacion');?></a></li>
						<li><a href="/frontend/index/proyectos/type/efimeros" class="parent no-child <?=($this->menu=='efimeros')?'current':'';?>"><?=$this->translate('efimeros');?></a></li>
						<li><a href="/frontend/index/proyectos/type/diseno" class="parent no-child <?=($this->menu=='diseno')?'current':'';?>"><?=$this->translate('diseño');?></a></li>
					</ul>
				</li>
				<li><a href="/frontend/index/publicaciones" class="parent no-child <?=($this->menu=='Publicaciones')?'current':'';?>"><?=$this->translate('Publicaciones');?></a></li>												
				<li><a href="/frontend/index/premios" class="parent no-child <?=($this->menu=='Premios')?'current':'';?>"><?=$this->translate('Premios');?></a></li>						
				<li><a href="/frontend/index/contacta" class="parent no-child <?=($this->menu=='Contacta')?'current':'';?>"><?=$this->translate('Contacta');?></a></li>						
			</ul>
		</div>
        <!-- .main_menu -->
		<div class="clear"></div>
		
			
		<!-- .footer -->		
		<div class="footer2">
			
			<!-- .socialbar -->
			<div class="socialbar-old">
				<?php
				if(isset(Zend_Auth::getInstance()->getIdentity()->user_name)
							and Zend_Auth::getInstance()->getIdentity()->user_name)				
				{
					echo "<a href=\"".$this->url(array('module' => 'users', 'controller'=>'author', 'action'=>'logoutandback'), 'default', true)."\">".$this->translate("Logout")."</a>";
					echo '<br/>'.$this->translate('Welcome').' '.@Zend_Auth::getInstance()->getIdentity()->user_name;		
				}		
				?>
				<div class="textbox">
						<form action="/frontend/index/search" method="post">
	                    <span class="search_input"><input type="text" id="txtsubscribe" value="<?=$this->translate('Buscar');?>:" onfocus="if(this.value == 'Buscar:') { this.value = ''; }" 
	                    	onblur="if(this.value == '') { this.value = '<?=$this->translate('Buscar');?>:'; }"
	                    	class="wpcf7-text wpcf7-validates-as-required" value="<?=$this->translate('Buscar');?>:" name="searchterm"></span>
	                    <span class="searcher"><a id="send" href="#" onClick="javascript:submit();">></a></span>
	                    </form>
	                    
	            </div>
            
            
			</div>
			<!-- .socialbar -->
					
			<div class="clear"></div>
			
			

		</div>
		<!-- .footer -->
	</div>
	<!-- .content -->		
	
	</div>
	<div id="sidebar">
		
		<!-- .pageright -->
		<div class="pageright1">
			<div class="pagetop">
				<div id="language"> 
		        <form name="langform" enctype="application/x-www-form-urlencoded" method="post" action="/default/index/changelanguage">    
					<input type="hidden" name="language" />
					<ul class="lang">
						<li><a href="#" title="Twitter" class="castellano" onClick="javascript:getsupport('es')">español</a></li>
						<li><a href="#" title="Twitter" class="catalá" onClick="javascript:getsupport('ca')">català</a></li>
						<li><a href="#" title="Twitter" class="english" onClick="javascript:getsupport('en')">english</a></li>		
					</ul>
					<input type="hidden" name="refer" value="<?=Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();?>" id="refer" />
				</form> 
				</div>		
			</div>
			<!-- #contentwrap -->
			<div id="contentwrap">
			<?= $this->layout()->content ?>
			<?= //$this->partial('menu.phtml', 'list', $pagerData) ?>
				
		
			</div>
			<!-- .contentwrap -->
		</div>
		<!-- .pageright -->
		
	</div>
	
</div>



<script language="JavaScript" type="text/javascript">
<!--
function getsupport ( selectedtype )
{
  document.langform.language.value = selectedtype ;
  document.langform.submit() ;
}
-->
</script> 



</body> 


</html>