<div id="generic_wrap" class="column span-16">
    <div id="generic_group">
        <h2><?=$this->translate("Remember password")?></h2>
        <?php if($this->failedRandomPassword): ?>
            <p><?=$this->translate("The password you typed does not match the one we sent to you")?></p>
        <?php endif; ?>
        <?php if($this->newPasswordSetOk): ?>
            <p><?=$this->translate("Password changed successfully")?></p>
        <?php else: ?>
            <p><?=$this->translate("Please enter the password we have sent you")?></p>
            <p>Tu email: <?= $this->email ?></p>
            <?= $this->form ?>
        <?php endif; ?>
        <p><a href="<?php echo $this->baseUrl();?>/author/login/">Login</a></p>
    </div><!-- end #generic_group -->
</div><!-- end #generic_wrap -->