<div id="footer">
    <div class="container">
      <div class="content">
        <div class="footer_left">©2007 - 2009 Orkestor. <?=$this->translate("All rights reserved");?>.</div>
        <div class="footer_right">
          <ul>
            <li class="first"><a href="#" title="" class="active"><span><span>HOME</span></span></a></li>
            <li><a href="#" title="" ><span><span>BLOG</span></span></a></li>
            <?php /*<li><a href="#" title="" ><span><span>TESTIMONIALS</span></span></a></li>
            <li><a href="#" title="" ><span><span>CONTACT</span></span></a></li>
            <li><a href="#" title="" ><span><span>Terms and Conditions</span></span></a></li>*/?>
          </ul>
        </div>
      </div>
    </div>
</div>