<div id="menu_row">
    <div class="container">
      <div class="content">
        <ul id="jsddm">
          <li><a href="/" title="" class="active"><span><span>HOME</span></span></a></li>
          <li><a href="/blog/index" title="" ><span><span>BLOG</span></span></a></li>          
          <?php /*<li><a href="testimonials.html" title="" ><span><span>TESTIMONIALS</span></span></a></li>
          <li><a href="contact.html" title="" ><span><span>CONTACT</span></span></a></li>  */?>   
          <li><a href="/admin" title="" ><span><span>LOGIN</span></span></a></li>       
        </ul>
      </div>
    </div>
    <br style="clear: both;"/>
  </div>