<h1>index</h1>

<div id="content">		
	<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" 
			codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" 
			width="100%" 
			height="100%" 
			id="swf" 
			align="middle">
		<param name="allowscriptaccess" value="samedomain" />
		<param name="allowfullscreen" value="true" />
		<param name="movie" value="klikteaseV.swf" />
		<param name="quality" value="high" />
		<param name="bgcolor" value="#000000" />

		<embed src="klikteaseV.swf" 
			   quality="high" 
			   bgcolor="#000000" 
			   width="100%" 
			   height="100%" 
			   name="swf" 
			   align="middle" 
			   allowscriptaccess="samedomain" 
			   allowfullscreen="true" 
			   type="application/x-shockwave-flash" 
			   pluginspage="http://www.macromedia.com/go/getflashplayer" />
	</object>
	
</div>
<object id="myId" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="100%" height="100%">
		<param name="movie" value="klikteaseV.swf">
		<embed src="klikteaseV.swf" width="550" height="400">
	</embed>
	</object>
<object id="myId" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="100%" height="100%">
		<param name="movie" value="klikteaseV.swf" />
        <!--[if !IE]>-->
		<object type="application/x-shockwave-flash" data="klikteaseV.swf" width="100%" height="100%">
		<!--<![endif]-->
		<div id="altContent">

			<h1>Alternative content</h1>
			<p><a href="http://www.adobe.com/go/getflashplayer"><img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" /></a></p>
		</div>
		<!--[if !IE]>-->
		</object>
		<!--<![endif]-->
	</object>