<!-- start : Picachoose jscripts and css -->
<link type="text/css" href="/styles/frontend/css/picachoose.css" rel="stylesheet" />
<script type="text/javascript" src="/styles/frontend/js/pikachoose.js"></script>
<script type="text/javascript">
	<!--
	$(document).ready(
		function (){
			$("#pikame").PikaChoose({auto_play:true});
	});
	-->
</script>
<!-- .scrollpanel -->
		<div class="scroll-pane">
			
			<!-- START : .SUBHEADER -->
			<div class="subheader">	
				<h1>Gallery Works!</h1>	
				<p class="simple">We are passionate about our works</p>				
				<h5>lorem ipsum dolor sit amet consectetur adipiscing elit. In hac habitasse platea dictumst Sed enim nulla mollis eu sagittis vitae, congue sed velit.</h5>
			</div>	
			<!-- END : .SUBHEADER -->
			
			<!-- START : .PICACHOOSE -->
			<div class="pikachoose">
				<ul id="pikame">
<li><a href="#"><img src="/styles/frontend/images/flickr1.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Consectetur adipiscing elit. Aliquam nisl arcu, porttitor vel tincidunt quisEtiam mollis </span></li>
<li><a href="#"><img src="/assets/images/portada/004_p.jpg" alt="" width="520" /></a><span><span class="imagetitle">Phasellus scelerisque</span>purus nec blandit molestie, nunc velit sagittis enim, a dignissim lacus nibh ac quam.</span></li>
<li><a href="#"><img src="/styles/frontend/images/flickr1.jpg" alt="" width="520" /></a><span><span class="imagetitle">Curabitur et tellus</span>ac ante egestas pellentesque sed in nunc. Phasellus venenatis fringilla eros.</span></li>
<li><a href="#"><img src="/styles/frontend/images/flickr2.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices varius nisl non tempor</span></li>																			
<li><a href="#"><img src="/styles/frontend/images/flickr1.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices varius nisl non tempor</span></li>
<li><a href="#"><img src="/styles/frontend/images/flickr2.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices varius nisl non tempor</span></li>
<li><a href="#"><img src="/styles/frontend/images/flickr1.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices varius nisl non tempor</span></li>
<li><a href="#"><img src="/styles/frontend/images/flickr2.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices varius nisl non tempor</span></li>																	
<li><a href="#"><img src="/styles/frontend/images/flickr1.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices varius nisl non tempor</span></li>
<li><a href="#"><img src="/styles/frontend/images/flickr1.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices varius nisl non tempor</span></li>
<li><a href="#"><img src="/styles/frontend/images/flickr2.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices varius nisl non tempor</span></li>																			
<li><a href="#"><img src="/styles/frontend/images/flickr1.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices varius nisl non tempor</span></li>
<li><a href="#"><img src="/styles/frontend/images/flickr2.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices varius nisl non tempor</span></li>
<li><a href="#"><img src="/styles/frontend/images/flickr1.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices varius nisl non tempor</span></li>
<li><a href="#"><img src="/styles/frontend/images/flickr2.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices varius nisl non tempor</span></li>																	
<li><a href="#"><img src="/styles/frontend/images/flickr1.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices varius nisl non tempor</span></li>
<li><a href="#"><img src="/styles/frontend/images/flickr1.jpg" alt="" width="520" /></a><span><span class="imagetitle">Lorem ipsum dolor</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices varius nisl non tempor</span></li>
</ul>
			</div>		
			<!-- END : .PICACHOOSE -->
			<div class="clear"></div>

			
		</div>
		<!-- END : #PANEL -->
