
	<!-- start : Picachoose jscripts and css -->


<link type="text/css" href="/styles/css/right/css/styles.css" rel="stylesheet" />

<script type="text/javascript" src="/scripts/js/jquery.pikachoose.js"></script>
<script type="text/javascript" src="/scripts/js/jquery.jcarousel.min.js"></script>

<script language="javascript">
	<!--
	$(document).ready(
		function (){
			$("#pikame").PikaChoose();

			$("#pikame").jcarousel({scroll:4,
				vertical:true,					
				initCallback: function(carousel) 
				{
			        $(carousel.list).find('img').click(function() {
			        	//console.log($(this).parents('.jcarousel-item').attr('jcarouselindex'));
			            carousel.scroll(parseInt($(this).parents('.jcarousel-item').attr('jcarouselindex')));
			        });
			    }
		    });
		});		
	-->
</script>

<!-- .scrollpanel -->
		<div class="scroll-pane">
		<?php foreach($this->entries as $entry) : ?>
			<!-- START : .PICACHOOSE -->
			<div class="pikachoose">				
				<ul id="pikame" class="jcarousel-skin-pika">
					<?php 
					$images=explode(',',$entry['images']);
					foreach($images as $image):
					?>
					<li>
						<img src="/assets/proyectos/<?=$entry['category_short'];?>/<?=$entry['short_name'];?>/<?=$image;?>"/>
					</li>
					<?php endforeach;?>
				</ul>
			</div>	
			<!-- END : .PICACHOOSE -->
			<div class="clear"></div>
			<!-- START : .SUBHEADER -->
			<div id = "infoag">
				<div class="subheader">	
					
						<?php if(isset(Zend_Auth::getInstance()->getIdentity()->user_name)
								and Zend_Auth::getInstance()->getIdentity()->user_name):?>	
						<div id="frontadmin">				
							<a target="_blank" href="<?php echo $this->url(array('module'=>'projects','controller'=>'index','action'=>'edit', 'project_id'=>$entry['id']));?>">Editar</a>
							<a target="_blank" href="<?php echo $this->url(array('module'=>'projects','controller'=>'index','action'=>'delete', 'project_id'=>$entry['id']), 'default');?>">Borrar</a>
						</div>
						<?php endif;?>
									
					<p class="simple">
						<?php echo $this->escape($entry['project']);?><br/>
						<?php echo $this->escape($entry['place']);?>, <?php echo $this->escape($entry['year']);?>
					</p>				
				</div>	
				<div class="two_third">
					<p>
					<?php echo $this->escape($entry['description']);?>
					</p>
				</div>
	<!--			<div class="one_third" ></div>-->
				<div class="one_third last">
									
					<?php if($entry['premio']!=''):?>
						<h5><?=$this->translate("Premios");?></h5>
						<p>
							<?php echo $this->escape($entry['premio']);?>
						</p>
					<?php endif;?>			
					
					<?php if($entry['cliente']!=''):?>
						<h5><?=$this->translate("Cliente");?></h5>
						<p>
							<?php echo $this->escape($entry['cliente']);?>
						</p>
					<?php endif;?>											
					
					<?php if($entry['associates']!=''):?>
						<h5><?=$this->translate("Asociados");?></h5>
						<p>
							<?php echo $this->escape($entry['associates']);?>
						</p>
					<?php endif;?>
					
					<?php if($entry['colaborators']!=''):?>
						<h5><?=$this->translate("Colaborando con");?></h5>
						<p>
							<?php echo $this->escape($entry['colaborators']);?>
						</p>
					<?php endif;?>
					
					<?php if($entry['consultors']!=''):?>
						<h5><?=$this->translate("Consultores");?></h5>
						<p>
							<?php echo $this->escape($entry['consultors']);?>
						</p>
					<?php endif;?>
					
					<?php if($entry['constructor']!=''):?>
						<h5><?=$this->translate("Constructor");?></h5>
						<p>
							<?php echo $this->escape($entry['constructor']);?>
						</p>
					<?php endif;?>
					
					
					<?php if($entry['area']!=''):?>
						<h5><?=$this->translate("Superficie");?></h5>
						<p>
							<?php echo $this->escape($entry['area']);?>
						</p>
					<?php endif;?>
										
					<?php if($entry['presupuesto']!=''):?>
						<h5><?=$this->translate("Presupuesto");?></h5>
						<p>
							<?php echo $this->escape($entry['presupuesto']);?>
						</p>
					<?php endif;?>
					
					<?php if($entry['photos']!=''):?>
						<h5><?=$this->translate("Fotografias");?></h5>
						<p>
							<?php echo $this->escape($entry['photos']);?>
						</p>
					<?php endif;?>
					
					<?php if($entry['pdf']!=''):?>
						<p>
							Descargar PDF<br/>
						</p>
					<?php endif;?>
												
				</div>
			</div>
			<!-- END : .SUBHEADER -->			
		<?php endforeach; ?>
		</div>
		<!-- END : #PANEL -->
