<h4>Paisaje</h4>
<ul class="proyectos">
	<li>
		<a href="/frontend/index/detalles/proyecto/5"><img src="/assets/proyectos/paisaje/gava/thumbnail.jpg" alt="image" /></a>
		<h4>Paseo Marítimo de Gava-Marinas</h4><span>Gavá<br/>1993</span>
	</li>
	<li>
		<a href="/frontend/index/detalles/proyecto/6"><img src="/assets/proyectos/paisaje/corredor_verd/thumbnail.jpg" alt="image" /></a>
		<h4>Corredor Verde de Cerdanyola</h4><span>Cerdanyola del Vallés<br/>2009</span>
	</li>				
	
</ul>

