<h4>Parques y jardines</h4>
<ul class="proyectos">
	<li>
		<a href="/frontend/index/detalles/proyecto/7"><img src="/assets/proyectos/parques_y_jardines/angel_guimera/thumbnail.jpg" alt="image" /></a>
		<h4>Jardines de Àngel Guimerà</h4><span>Barcelona<br/>1998</span>
	</li>
	<li>
		<a href="/frontend/index/detalles/proyecto/8"><img src="/assets/proyectos/parques_y_jardines/rodrigo_caro/thumbnail.jpg" alt="image" /></a>
		<h4>Jardines Rodrigo Caro</h4><span>Barcelona<br/>2007</span>
	</li>				
	<li class="last">
		<a href="/frontend/index/detalles/proyecto/9"><img src="/assets/proyectos/parques_y_jardines/la_clota/thumbnail.jpg" alt="image" /></a>
		<h4>Parque de La Clota</h4><span>Sabadell<br/>2009</span>
	</li>
</ul>

