<div class="scroll-pane">
<ul class="proyectos">
	<li>
		<a href="/frontend/index/detalles/proyecto/2"><img src="/assets/proyectos/planeamiento/zonas_verds_hospitalet/thumbnail.jpg" alt="image" /></a>
		<h4>Plan Director dels Espais Verds</h4><span>L’Hospitalet de Llobregat, 2005</span>
	</li>
	<li>
		<a href="/frontend/index/detalles/proyecto/3"><img src="/assets/proyectos/planeamiento/miguel_servet/thumbnail.jpg" alt="image" /></a>
		<h4>Plan Director del Parque Miguel Servet</h4><span>Huesca, 2007</span>
	</li>				
	<li class="last">
		<a href="/frontend/index/detalles/proyecto/4"><img src="/assets/proyectos/planeamiento/prat_nord/thumbnail.jpg" alt="image" /></a>
		<h4>Prat Nord - Concurso restringido</h4><span>El Prat de Llobregat, 2008</span>
	</li>
</ul>
<ul class="proyectos">
	<li>
		<a href="/frontend/index/detalles/proyecto/2"><img src="/assets/proyectos/planeamiento/zonas_verds_hospitalet/thumbnail.jpg" alt="image" /></a>
		<h4>Plan Director dels Espais Verds</h4><span>L’Hospitalet de Llobregat, 2005</span>
	</li>
	<li>
		<a href="/frontend/index/detalles/proyecto/3"><img src="/assets/proyectos/planeamiento/miguel_servet/thumbnail.jpg" alt="image" /></a>
		<h4>Plan Director del Parque Miguel Servet</h4><span>Huesca, 2007</span>
	</li>				
	<li class="last">
		<a href="/frontend/index/detalles/proyecto/4"><img src="/assets/proyectos/planeamiento/prat_nord/thumbnail.jpg" alt="image" /></a>
		<h4>Prat Nord - Concurso restringido</h4><span>El Prat de Llobregat, 2008</span>
	</li>
</ul>
</div>

