<!-- .scrollpanel -->
		<div class="scroll-pane">
<h4>Publicaciones</h4>
<ul class="proyectos">
	<li>
		<img src="/assets/images/publications/1_Arquitecturas_BIS_n28-29_i_43.jpg" alt="image" />
		<h4>Arquitecturas BIS no 28-29 i 43</h4>
	</li>
	<li>
		<img src="/assets/images/publications/11_FAD_1989.jpg" alt="image" />
		<h4>Arquitecturas BIS no 28-29 i 43</h4>
	</li>				
	<li>
		<img src="/assets/images/publications/15_on_122_Avinyo.jpg" alt="image" />
		<h4>Arquitecturas BIS no 28-29 i 43</h4>
	</li>
</ul>
<ul class="proyectos">
	<li>
		<img src="/assets/images/publications/18_FAD_1993.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/19_ON_164_Joies.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/20_La_Conquesta del Verd_Can Sabater.jpg" alt="image" />
		<h4></h4>
	</li>
</ul>
<ul class="proyectos">
	<li>
		<img src="/assets/images/publications/2003_Neutra_9-10_Observatoris_Aiguamolls.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/2004_Il_progetto_del_vuoto_Meson_Gitano.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/2008_Nosotras_las_ciudades_Meson_Gitano.jpg" alt="image" />
		<h4></h4>
	</li>
</ul>
<ul class="proyectos">
	<li>
		<img src="/assets/images/publications/21_FAD_1994.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/22_III_Bienal_Arq_espanola.gif" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/23_topos_10.jpg" alt="image" />
		<h4></h4>
	</li>
</ul>
<ul class="proyectos">
	<li>
		<img src="/assets/images/publications/24_Domus_770_Gava.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/25_Trienal_Mila.JPG" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/26_Around_Barcelona_CD_Gava.gif" alt="image" />
		<h4></h4>
	</li>
</ul>
<ul class="proyectos">
	<li>
		<img src="/assets/images/publications/27_DeltaADI-FAD_95.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/28_I_Biennal_Paisatge.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/29_VI_Bienal_Arq_espanola.gif" alt="image" />
		<h4></h4>
	</li>
</ul>
<ul class="proyectos">
	<li>
		<img src="/assets/images/publications/3_Editions_du_Moniteur_1981.jpeg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/30_FAD_2000_Angel_guimera.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/31_Il_Parco_pubblico_Angel_Guimera.jpg" alt="image" />
		<h4></h4>
	</li>
</ul>
<ul class="proyectos">
	<li>
		<img src="/assets/images/publications/32_Casabella_695_Angel_Guimera.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/33_Jardins_Insurgents_Parc_Solidaritat.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/33_on_215_Angel_Guimera.jpg" alt="image" />
		<h4></h4>
	</li>
</ul>
<ul class="proyectos">
	<li>
		<img src="/assets/images/publications/34_VIA_Arquitectura_Angel_Guimera.JPG" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/35_Casabella_712_Joies_i_altres.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/36_Landscape_Design_Today_Angel_Guimera.jpg" alt="image" />
		<h4></h4>
	</li>
</ul>
<ul class="proyectos">
	<li>
		<img src="/assets/images/publications/37_FAD_2004_Meson_Gitano.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/38_ON_253_Meson_Gitano.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/39_Imma_Jansana_libria.jpg" alt="image" />
		<h4></h4>
	</li>
</ul>
<ul class="proyectos">
	<li>
		<img src="/assets/images/publications/4_Plans_i_projectes_per_a_Barcelona_1981-1982.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/40_Paisea_08_Cauces_Palmones.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/41_Casabella_784_Torre_Llobregat.jpg" alt="image" />
		<h4></h4>
	</li>
</ul>
<ul class="proyectos">
	<li>
		<img src="/assets/images/publications/6_on_70.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/Arco_Colour_Landscape_Gava.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/Casabella_732_Meson_Gitano.jpg" alt="image" />
		<h4></h4>
	</li>
</ul>
<ul class="proyectos">
	<li>
		<img src="/assets/images/publications/Catalunya_Arquitectura_Gava.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/ON_296_Cims_Montjuic.jpg" alt="image" />
		<h4></h4>
	</li>
	<li>
		<img src="/assets/images/publications/Paisajismo_7_Meson_Gitano.png" alt="image" />
		<h4></h4>
	</li>
</ul>	
<ul class="proyectos">
	<li>
		<img src="/assets/images/publications/17_Quaderns_Guia_dArquitectura_BCN.jpg" alt="image" />
		<h4></h4>
	</li>
</ul>	
		</div>
		<!-- END : #PANEL -->


